apiVersion: apps/v1
kind: Deployment
metadata:
  name: eplink-payment
  labels:
    name:  payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - image: safeerep/payment:latest
        name: payment-service
        envFrom:
          - configMapRef:
              name: payment-config