apiVersion: v1
kind: Service
metadata:
  name:  eplink-payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name: payment-service
    protocol: TCP
    port:  3004
    targetPort: 3004