apiVersion: v1
kind: Service
metadata:
  name:  eplink-rabbitmq-service
spec:
  selector:
    app: rabbitmq-service
  ports:
  - name: tcp-amqp
    port:  5672
    targetPort: 5672
  - name: http-management
    port:  15672
    targetPort: 15672