apiVersion: apps/v1
kind: Deployment
metadata:
  name: eplink-chat
  labels:
    name:  chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - image: safeerep/chat:latest
        name: chat-service
        envFrom:
          - configMapRef:
              name: chat-config