apiVersion: v1
kind: Service
metadata:
  name:  eplink-product-service
spec:
  selector:
    app: product-service
  ports:
  - name: product-service
    protocol: TCP
    port:  3002
    targetPort: 3002